// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaHybrid.Infrastructure.Data;

#nullable disable

namespace WaHybrid.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HybridDbContext))]
    [Migration("20260831084013_InitialHybridSchema")]
    partial class InitialHybridSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WaHybrid.Domain.Entities.Campaign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_template");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("estimated_cost_usd");

                    b.Property<string>("IntentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("intent_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<int>("PlannedOfficial")
                        .HasColumnType("int")
                        .HasColumnName("planned_official");

                    b.Property<int>("PlannedSkipped")
                        .HasColumnType("int")
                        .HasColumnName("planned_skipped");

                    b.Property<int>("PlannedUnofficial")
                        .HasColumnType("int")
                        .HasColumnName("planned_unofficial");

                    b.Property<string>("Segment")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("segment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.CostLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BspFeeUsd")
                        .HasPrecision(14, 6)
                        .HasColumnType("decimal(14,6)")
                        .HasColumnName("bsp_fee_usd");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(14, 6)
                        .HasColumnType("decimal(14,6)")
                        .HasColumnName("cost_usd");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("country_code");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Delivered")
                        .HasColumnType("int")
                        .HasColumnName("delivered");

                    b.Property<int>("MetaCategory")
                        .HasColumnType("int")
                        .HasColumnName("meta_category");

                    b.Property<int>("MsgCount")
                        .HasColumnType("int")
                        .HasColumnName("msg_count");

                    b.HasKey("Id");

                    b.HasIndex("Day", "Channel", "MetaCategory", "CountryCode")
                        .IsUnique();

                    b.ToTable("cost_ledger", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AcquisitionSource")
                        .HasColumnType("int")
                        .HasColumnName("acquisition_source");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CtwaClid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ctwa_clid");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<int?>("LastChannelUsed")
                        .HasColumnType("int")
                        .HasColumnName("last_channel_used");

                    b.Property<decimal>("Monetary")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("monetary");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<bool>("OfficialOptIn")
                        .HasColumnType("bit")
                        .HasColumnName("official_opt_in");

                    b.Property<DateTimeOffset?>("OfficialOptInAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("official_opt_in_at");

                    b.Property<string>("OptInSource")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("opt_in_source");

                    b.Property<bool>("OptedIn")
                        .HasColumnType("bit")
                        .HasColumnName("opted_in");

                    b.Property<DateTimeOffset?>("OptedInAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("opted_in_at");

                    b.Property<bool>("OptedOut")
                        .HasColumnType("bit")
                        .HasColumnName("opted_out");

                    b.Property<DateTimeOffset?>("OptedOutAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("opted_out_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("PreferredChannel")
                        .HasColumnType("int")
                        .HasColumnName("preferred_channel");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<int>("RecencyDays")
                        .HasColumnType("int")
                        .HasColumnName("recency_days");

                    b.Property<string>("Segment")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("segment");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Segment");

                    b.HasIndex("OptedIn", "OptedOut");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.CustomerWindow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ChannelSeen")
                        .HasColumnType("int")
                        .HasColumnName("channel_seen");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_at");

                    b.Property<int>("Kind")
                        .HasColumnType("int")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("opened_at");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("opened_by");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RenewCount")
                        .HasColumnType("int")
                        .HasColumnName("renew_count");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("source_ref");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Kind")
                        .IsUnique();

                    b.HasIndex("Phone", "ExpiresAt");

                    b.ToTable("customer_windows", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.MessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CampaignId")
                        .HasColumnType("bigint")
                        .HasColumnName("campaign_id");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<decimal?>("CostBilled")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("cost_billed");

                    b.Property<decimal>("CostEstimated")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("cost_estimated");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DelayUsedMs")
                        .HasColumnType("int")
                        .HasColumnName("delay_used_ms");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("delivered_at");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("direction");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<int?>("FallbackFrom")
                        .HasColumnType("int")
                        .HasColumnName("fallback_from");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("intent");

                    b.Property<int>("MetaCategory")
                        .HasColumnType("int")
                        .HasColumnName("meta_category");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("read_at");

                    b.Property<string>("RouteReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("route_reason");

                    b.Property<int>("SendMode")
                        .HasColumnType("int")
                        .HasColumnName("send_mode");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("sent_at");

                    b.Property<string>("SessionId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("template_name");

                    b.Property<string>("WaMessageId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("wa_message_id");

                    b.Property<int>("WindowState")
                        .HasColumnType("int")
                        .HasColumnName("window_state");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[idempotency_key] IS NOT NULL");

                    b.HasIndex("Phone");

                    b.HasIndex("Channel", "CreatedAt");

                    b.ToTable("message_log", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.OfficialStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<int>("DailyLimit")
                        .HasColumnType("int")
                        .HasColumnName("daily_limit");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumberId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("phone_number_id");

                    b.Property<int>("QualityRating")
                        .HasColumnType("int")
                        .HasColumnName("quality_rating");

                    b.Property<DateTimeOffset?>("ResetAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reset_at");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tier");

                    b.Property<int>("UsedToday")
                        .HasColumnType("int")
                        .HasColumnName("used_today");

                    b.HasKey("Id");

                    b.ToTable("official_status", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.SuppressionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("reason");

                    b.Property<int?>("SeenOnChannel")
                        .HasColumnType("int")
                        .HasColumnName("seen_on_channel");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("suppression_list", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.WaSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyQuota")
                        .HasColumnType("int")
                        .HasColumnName("daily_quota");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ProxyLabel")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("proxy_label");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int")
                        .HasColumnName("risk_score");

                    b.Property<int>("SentToday")
                        .HasColumnType("int")
                        .HasColumnName("sent_today");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("WarmupDay")
                        .HasColumnType("int")
                        .HasColumnName("warmup_day");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("wa_sessions", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.WaTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("approved_at");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_text");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("footer_text");

                    b.Property<string>("HeaderKind")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("header_kind");

                    b.Property<string>("Intent")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("intent");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MetaId")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("meta_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PausedUntil")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("paused_until");

                    b.Property<int?>("Quality")
                        .HasColumnType("int")
                        .HasColumnName("quality");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("RequiredParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("required_params_json");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Intent", "Status");

                    b.ToTable("wa_templates", (string)null);
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.CustomerWindow", b =>
                {
                    b.HasOne("WaHybrid.Domain.Entities.Customer", "Customer")
                        .WithMany("Windows")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WaHybrid.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
